name: Submit Reading

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "BOOK=$(echo $GITHUB_CONTEXT | jq '.book' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "CHAPTER=$(echo $GITHUB_CONTEXT | jq '.chapter' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "SPEAKER=$(echo $GITHUB_CONTEXT | jq '.speaker' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "GRAVATAR_HASH=$(echo $GITHUB_CONTEXT | jq '.gravatarHash' -r)" >> $GITHUB_ENV
    - env:
        GITHUB_CONTEXT: ${{ github.event.client_payload.data }}
      run: echo "VIDEOID=$(echo $GITHUB_CONTEXT | jq '.videoId' -r)" >> $GITHUB_ENV
    - name: Writing Snippet to File
      run: node saveRecording.js
    - name: Committing changes with rebase
      id: push
      continue-on-error: true
      uses: benkaiser/rebase-commit-push@v1.1
      with:
        author_name: Github Actions
        author_email: actions@github.com
    - name: Retry Push 1
      continue-on-error: true
      id: retry1
      if: steps.push.outcome=='failure'
      uses: benkaiser/rebase-commit-push@v1.1
      with:
        author_name: Github Actions
        author_email: actions@github.com
    - name: Retry Push 2
      continue-on-error: true
      id: retry2
      if: steps.retry1.outcome=='failure'
      uses: benkaiser/rebase-commit-push@v1.1
      with:
        author_name: Github Actions
        author_email: actions@github.com
    - name: Retry Push 3
      continue-on-error: true
      id: retry3
      if: steps.retry2.outcome=='failure'
      uses: benkaiser/rebase-commit-push@v1.1
      with:
        author_name: Github Actions
        author_email: actions@github.com
    - name: set the status
      if: always()
      run: |
        if ${{ steps.push.outcome=='success' || steps.retry1.outcome=='success' || steps.retry2.outcome=='success' || steps.retry3.outcome=='success' }}; then
            echo fine
        else
            exit 1
        fi